### PR TITLE
[ADD] Testcases(zip, textfile, excel)

### PR DESCRIPTION
**Pull request by ssccinng**
Several use cases have been tried, and it is not clear how to use xmlfile and create zip

### CODE REVIEW

**Comment by paillave** [comment]
Thanks a lot for this pull request. However, it would be great that, instead of using a new console project, you could change it into an xunit test project. If you can't (or don't have time for it) do so, let me know, I'll amend your PR when I have time3.

**Comment by ssccinng** [comment]
> Thanks a lot for this pull request. However, it would be great that, instead of using a new console project, you could change it into an xunit test project. If you can't (or don't have time for it) do so, let me know, I'll amend your PR when I have time.

ok, I'll try

**Comment by paillave** [comment]
> > Thanks a lot for this pull request. However, it would be great that, instead of using a new console project, you could change it into an xunit test project. If you can't (or don't have time for it) do so, let me know, I'll amend your PR when I have time.
> 
> ok, I'll try

Fantastic. It is very appreciated :smile: . Once again, if U don't feel like it, I'll do it myself a bit later.

**Comment by ssccinng** [comment]
> > > Thanks a lot for this pull request. However, it would be great that, instead of using a new console project, you could change it into an xunit test project. If you can't (or don't have time for it) do so, let me know, I'll amend your PR when I have time.
> > 
> > 
> > ok, I'll try
> 
> Fantastic. It is very appreciated 😄 . Once again, if U don't feel like it, I'll do it myself a bit later.

I'm very happy to do these works. On the contrary, because I am not experienced enough, I may make some stupid operations. I will be very happy if I can get suggestions!😉

**Pull request closed without merging**
